# -*- coding: utf-8 -*-
"""AnaliseClientesBanco.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10-q9mk5vohvLH8yETD8CeuOmFjmt8ymj
"""


"""1-importar base de dados

2-visualizar e tratar base de dados(colunasInuteis,desformatadas)

3-dar uma olhada na base de dados

4- Construir uma analise para indentificar o motivo de cancelamento

"""

import pandas as pd

tabela = pd.read_csv('ClientesBancos.csv', encoding="latin1")
tabela = tabela.drop('CLIENTNUM', axis=1)
print(tabela)

#Tratar valores vazios

tabela = tabela.dropna()
tabela.info()

tabela.describe().round(1)

#avaliar a divisão entre Clientes x Cancelados

qtd_categoria = tabela['Categoria'].value_counts()
print(qtd_categoria)
qtd_categoria_perc = tabela['Categoria'].value_counts(normalize=True)
print(qtd_categoria_perc)

import plotly.express as px

grafico = px.histogram(tabela, x="Idade", color='Categoria')
grafico.show()

import plotly.express as px

for coluna in tabela:  #percorre coluna, para percorrer linha seria -for linha in tabela.index:
    grafico = px.histogram(tabela, x=coluna, color='Categoria')
    grafico.show()

"""Informações retiradas da visualização dos gráficos:

-Quanto mais produtos contratados um cliente tem, menor a chance de cancelar

-Quanto mais transações e quanto maior o valor de transação, menor a chance de cancelar.

-O genêro femenino tem maior cancelamento

-Quanto mais vezes entra em contato com o banco maior a chance de cancelar

-Maior cancelamento; Cartão Blue
"""
